/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jFram;


import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.Statement;
import javax.swing.JOptionPane;


import javax.swing.text.TableView;

/**
 *
 * @author Joel Arriola
 */
public class MostrarDatos extends javax.swing.JPanel {

    /**
     * Creates new form MostrarDatos
     */
    public MostrarDatos() {
        initComponents();
        lista(tbLista);
    }
void lista(JTable ParametroLista){
    
    Conexion Conectar=new Conexion();
    Connection ConectarBD=Conectar.Conectar();
    DefaultTableModel modelo =new DefaultTableModel();//creamos modelo esta vacio
    TableRowSorter<TableModel> OrdenarTabla=new TableRowSorter<TableModel>(modelo);
    ParametroLista.setRowSorter(OrdenarTabla);// ordenado
    
    String query="select *from usuario";
    modelo.addColumn("idUsuario");
    modelo.addColumn("Usuario");
    modelo.addColumn("Contraseña");
    ParametroLista.setModel(modelo);// a nuestra variable le pasamos el modelo
      
    String[] Datos=new String[3];
    Statement Guardar;
    try {
        Guardar=Conectar.Conectar().createStatement();
        ResultSet mostrar;
        mostrar=Guardar.executeQuery(query);
        while(mostrar.next()){
            Datos[0]=mostrar.getString(1);
            Datos[1]=mostrar.getString(2);
            Datos[2]=mostrar.getString(3);
            modelo.addRow(Datos);
            
            
        }
        ParametroLista.setModel(modelo);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "NO SE PUEDEN MOSTRAR LOS REGISTROS"+e.toString());
    }
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbLista.setBackground(new java.awt.Color(255, 204, 204));
        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 470));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 470));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    // End of variables declaration//GEN-END:variables
}
